/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tshirt.glb 
Author: Tabbuso (https://sketchfab.com/Tabbuso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tshirt-5a21282b2e454d1696547148f617d3d0
Title: Tshirt
*/

import { useGLTF,useTexture  } from '@react-three/drei'
import { useEffect, useState } from 'react'

export function Tshirt(props) {

    const { nodes } = useGLTF('/models/tshirt.glb'); // Load the 3D model
    const [imageTexture, setImageTexture] = useState(null); // State to store the texture for the t-shirt
  
    const clothId = 'sews96b5mvq'; // You can replace this with dynamic logic to fetch the cloth ID
  
    useEffect(() => {
      const storedData = localStorage.getItem(clothId); // Retrieve the cloth object using its ID
  
      if (storedData) {
        const parsedData = JSON.parse(storedData); // Parse the stored object
        if (parsedData && parsedData.image) {
          setImageTexture(parsedData.image); // Set the image URL from the 'image' key in the object
        }
      }
    }, [clothId]);
  
    // Use the Base64 image directly for texture
    const texture = useTexture( imageTexture || '/red.jpg'); // If no Base64 data, fallback to default image
  
    return (
      <group {...props} dispose={null}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.039}>
          <mesh geometry={nodes.Object_4.geometry}>
            <meshStandardMaterial map={texture} />
          </mesh>
          <mesh geometry={nodes.Object_5.geometry}>
            <meshStandardMaterial map={texture} />
          </mesh>
          <mesh geometry={nodes.Object_6.geometry}>
            <meshStandardMaterial map={texture} />
          </mesh>
          <mesh geometry={nodes.Object_7.geometry}>
            <meshStandardMaterial map={texture} />
          </mesh>
        </group>
      </group>
    )
}

useGLTF.preload('/models/tshirt.glb')
